### ISSUE TITLE
"missing = in const declaration" Firefox issue

### ISSUE THREAD

**Issue by jrmiddleton** [HubSpot/humanize#77]
Whilst trying to use the library in Firefox I am seeing the following error:

```missing = in const declaration```

Looks like it caused by the following:

```
const a; now throws a SyntaxError ("missing = in const declaration"): An initializer is required.
```
ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const

Problem line is on 141 and is:

```
for (const label in LABELS_FOR_POWERS_OF_KILO) {
```

**Comment by geekjuice** [comment]
Seems like you are using the non-compiled code. The files you want to use are in the [dist](https://github.com/HubSpot/humanize/tree/master/dist) directory.
