### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by gshackles** [HubSpot/humanize#81]
I've started working with humanize as part of a TypeScript application, and ended up just going ahead and creating definitions for all the exposed methods. Is this something you'd be willing to include directly in the repository and npm package? If so I'm happy to submit a PR with the changes. If not I can create and maintain a separate typings repository to host the definitions, but it's a much better user experience to have it directly in the package. 

Let me know! 😄

**Comment by jc0n** [comment]
+1

**Comment by DenisCarriere** [comment]
@gshackles have you move ahead with this? I've got a working typescript definition with tests I can push right now.

**Comment by DenisCarriere** [comment]
https://github.com/HubSpot/humanize/pull/92/files

**Comment by gshackles** [comment]
Looks like that should take care of this, thanks! 😄  Any ETA for that making it out into a release?

**Comment by DenisCarriere** [comment]
@gshackles The definitions is already published to`@types/humanize-plus`, you can start using it right now 🎉 !

Feel free to send PR's to DT and I can 👍 the changes.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16977

https://www.npmjs.com/package/@types/humanize-plus

**Comment by gshackles** [comment]
Ah awesome. That said, in #92 you added the type definitions directly into this repository, so even better would be to push an updated package out that includes that definition and avoid the need for pulling in the separate definition from DT 😀

**Comment by DenisCarriere** [comment]
You are correct, however no one merges anything in this library, unless you have admin privileges to merge?

**Comment by DenisCarriere** [comment]
I opened that PR March 3rd

**Comment by gshackles** [comment]
Doh, sorry, that's what I get for reading too quickly...I saw the closed PR but missed the fact that it wasn't actually merged. In that case, I suppose the typing will do the trick for now!

**Comment by DenisCarriere** [comment]
👍 Yea... if you can convince the maintainers of this library to merge or accept a Typescript definition, we can make another PR.

**Comment by FranDias** [comment]
Hey, someone with admin privileges here—

Internally we merged this with our larger i18n library so it's a bit of a split for us to maintain both. You're more than welcome to fork and maintain & I'm happy to work with whoever wants to get things pointed there.

**Comment by gshackles** [comment]
Whoops missed this til now. Thanks for the response, @FranDias!

If this isn't really being updated anymore then I think just leaving the separate type package seems reasonable. We don't have a real need to fork/maintain at this point, but if the need arises we can revisit.

Closing this issue out then, thanks all!
